/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-03-14 13:27:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<title>KKIRI(끼리)</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/js/index.js\"></script>\r\n");
      out.write("\t\t<div id=\"container\">\r\n");
      out.write("          <!-- 배너 start -->\r\n");
      out.write("          <div id=\"banner\">\r\n");
      out.write("            <div class=\"banner-text-area\">\r\n");
      out.write("              <p class=\"banner-title\">\r\n");
      out.write("                많은 사람들이 끼리를 통해 삶을 공유하고 있습니다.<br>\r\n");
      out.write("                <span class=\"banner-sub-title\">내 주변의 사람들과 좋아하는 일을 함께 하며 새로운 경험을 즐겨 보세요.</span>\r\n");
      out.write("              </p>\r\n");
      out.write("              <a href=\"#\" class=\"go-sign-up\">끼리 가입하기</a>\r\n");
      out.write("            </div>\r\n");
      out.write("    \t\t\t\t<video class='video' autoplay loop muted>\r\n");
      out.write("    \t\t\t\t\t<source src='");
      out.print(request.getContextPath() );
      out.write("/resources/movie/banner-movie.mp4' type='video/mp4'>\r\n");
      out.write("    \t\t\t\t</video>\r\n");
      out.write("            <div class=\"video-shadow\"> </div>\r\n");
      out.write("      \t\t</div>\r\n");
      out.write("          <!-- 배너 end -->\r\n");
      out.write("\r\n");
      out.write("          <!-- 이런 이벤트는 어떠세요? start -->\r\n");
      out.write("          <div id=\"event-recommend\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <!-- 이벤트 상세페이지 들어가기 Test용 start-->\r\n");
      out.write("                <h5>\r\n");
      out.write("                \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/event/detail\">\r\n");
      out.write("                \t\t이벤트 상세페이지 들어가기 테스트용입니다 (삭제 예정)\r\n");
      out.write("                \t</a>\r\n");
      out.write("                </h5>\r\n");
      out.write("                <!-- 이벤트 상세페이지 들어가기 Test용 start-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                  <h3 class=\"box-title\">\r\n");
      out.write("                    이런 이벤트 어떠세요?<br>\r\n");
      out.write("                    <span class=\"box-sub-title\">끼리에 가입하고 이벤트에 참여하세요.</span>\r\n");
      out.write("                  </h3>\r\n");
      out.write("                  <div class=\"blog-slider\">\r\n");
      out.write("                    <div class=\"blog-slider__wrp swiper-wrapper\">\r\n");
      out.write("                      <div class=\"blog-slider__item swiper-slide on\">\r\n");
      out.write("                        <div class=\"blog-slider__img\">\r\n");
      out.write("                          <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/thumbnail1.PNG\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"blog-slider__content\">\r\n");
      out.write("                          <span class=\"blog-slider__code\">2020년 02월 21일 19:00</span>\r\n");
      out.write("                          <div class=\"blog-slider__title\">\r\n");
      out.write("                            <p class=\"address\">[같이 등산가요1]</p>\r\n");
      out.write("                            <p class=\"location\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/map-ping.png\" alt=\"위치\"> &nbsp;서울시 중구 다산로</p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"blog-slider__text\">\r\n");
      out.write("                            <p class=\"leader\">주최자</p>\r\n");
      out.write("                            <div class=\"content\">\r\n");
      out.write("                              <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/profile-ex.png\" alt=\"프로필\" class=\"profile-img\">\r\n");
      out.write("                              <p class=\"leader-info\">\r\n");
      out.write("                                주최자 닉네임<br>\r\n");
      out.write("                                <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/star-on.png\" alt=\"별점\" class=\"star-img\">\r\n");
      out.write("                                <span class=\"star-rating\">4.2</span>\r\n");
      out.write("                              </p>\r\n");
      out.write("                              <p class=\"member-count\">참석인원 : 4/10</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p class=\"ticket\">티켓 : 4장</p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"blog-slider__item swiper-slide\">\r\n");
      out.write("                        <div class=\"blog-slider__img\">\r\n");
      out.write("                          <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/thumbnail2.PNG\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"blog-slider__content\">\r\n");
      out.write("                          <span class=\"blog-slider__code\">2020년 02월 21일 19:00</span>\r\n");
      out.write("                          <div class=\"blog-slider__title\">\r\n");
      out.write("                            <p class=\"address\">[같이 등산가요2]</p>\r\n");
      out.write("                            <p class=\"location\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/map-ping.png\" alt=\"위치\"> &nbsp;서울시 중구 다산로</p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"blog-slider__text\">\r\n");
      out.write("                            <p class=\"leader\">주최자</p>\r\n");
      out.write("                            <div class=\"content\">\r\n");
      out.write("                              <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/profile-ex.png\" alt=\"프로필\" class=\"profile-img\">\r\n");
      out.write("                              <p class=\"leader-info\">\r\n");
      out.write("                                주최자 닉네임<br>\r\n");
      out.write("                                <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/star-on.png\" alt=\"별점\" class=\"star-img\">\r\n");
      out.write("                                <span class=\"star-rating\">4.2</span>\r\n");
      out.write("                              </p>\r\n");
      out.write("                              <p class=\"member-count\">참석인원 : 4/10</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p class=\"ticket\">티켓 : 4장</p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"blog-slider__item swiper-slide\">\r\n");
      out.write("                        <div class=\"blog-slider__img\">\r\n");
      out.write("                          <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/thumbnail3.PNG\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"blog-slider__content\">\r\n");
      out.write("                          <span class=\"blog-slider__code\">2020년 02월 21일 19:00</span>\r\n");
      out.write("                          <div class=\"blog-slider__title\">\r\n");
      out.write("                            <p class=\"address\">[같이 등산가요3]</p>\r\n");
      out.write("                            <p class=\"location\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/map-ping.png\" alt=\"위치\"> &nbsp;서울시 중구 다산로</p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"blog-slider__text\">\r\n");
      out.write("                            <p class=\"leader\">주최자</p>\r\n");
      out.write("                            <div class=\"content\">\r\n");
      out.write("                              <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/profile-ex.png\" alt=\"프로필\" class=\"profile-img\">\r\n");
      out.write("                              <p class=\"leader-info\">\r\n");
      out.write("                                주최자 닉네임<br>\r\n");
      out.write("                                <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/star-on.png\" alt=\"별점\" class=\"star-img\">\r\n");
      out.write("                                <span class=\"star-rating\">4.2</span>\r\n");
      out.write("                              </p>\r\n");
      out.write("                              <p class=\"member-count\">참석인원 : 4/10</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p class=\"ticket\">티켓 : 4장</p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"blog-slider__item swiper-slide\">\r\n");
      out.write("                        <div class=\"blog-slider__img\">\r\n");
      out.write("                          <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/thumbnail1.PNG\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"blog-slider__content\">\r\n");
      out.write("                          <span class=\"blog-slider__code\">2020년 02월 21일 19:00</span>\r\n");
      out.write("                          <div class=\"blog-slider__title\">\r\n");
      out.write("                            <p class=\"address\">[같이 등산가요4]</p>\r\n");
      out.write("                            <p class=\"location\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/map-ping.png\" alt=\"위치\"> &nbsp;서울시 중구 다산로</p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"blog-slider__text\">\r\n");
      out.write("                            <p class=\"leader\">주최자</p>\r\n");
      out.write("                            <div class=\"content\">\r\n");
      out.write("                              <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/profile-ex.png\" alt=\"프로필\" class=\"profile-img\">\r\n");
      out.write("                              <p class=\"leader-info\">\r\n");
      out.write("                                주최자 닉네임<br>\r\n");
      out.write("                                <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/star-on.png\" alt=\"별점\" class=\"star-img\">\r\n");
      out.write("                                <span class=\"star-rating\">4.2</span>\r\n");
      out.write("                              </p>\r\n");
      out.write("                              <p class=\"member-count\">참석인원 : 4/10</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p class=\"ticket\">티켓 : 4장</p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"blog-slider__item swiper-slide\">\r\n");
      out.write("                        <div class=\"blog-slider__img\">\r\n");
      out.write("                          <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/thumbnail2.PNG\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"blog-slider__content\">\r\n");
      out.write("                          <span class=\"blog-slider__code\">2020년 02월 21일 19:00</span>\r\n");
      out.write("                          <div class=\"blog-slider__title\">\r\n");
      out.write("                            <p class=\"address\">[같이 등산가요5]</p>\r\n");
      out.write("                            <p class=\"location\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/map-ping.png\" alt=\"위치\"> &nbsp;서울시 중구 다산로</p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"blog-slider__text\">\r\n");
      out.write("                            <p class=\"leader\">주최자</p>\r\n");
      out.write("                            <div class=\"content\">\r\n");
      out.write("                              <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/profile-ex.png\" alt=\"프로필\" class=\"profile-img\">\r\n");
      out.write("                              <p class=\"leader-info\">\r\n");
      out.write("                                주최자 닉네임<br>\r\n");
      out.write("                                <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/star-on.png\" alt=\"별점\" class=\"star-img\">\r\n");
      out.write("                                <span class=\"star-rating\">4.2</span>\r\n");
      out.write("                              </p>\r\n");
      out.write("                              <p class=\"member-count\">참석인원 : 4/10</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p class=\"ticket\">티켓 : 4장</p>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"blog-slider__pagination swiper-pagination-bullets\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- 이런 이벤트는 어떠세요? end -->\r\n");
      out.write("\r\n");
      out.write("          <!-- 주최자 랭킹 start -->\r\n");
      out.write("          <div id=\"ranking\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                  <h3 class=\"box-title\">\r\n");
      out.write("                    한주간 가장 높은 평점을 받은 5명을 소개합니다.<br>\r\n");
      out.write("                    <span class=\"box-sub-title\">축하드립니다! 앞으로도 멋진 모임들을 많이 만들어주세요.</span>\r\n");
      out.write("                  </h3>\r\n");
      out.write("                    <div class=\"ranking-wrap\">\r\n");
      out.write("                      <ul class=\"ranker-list\">\r\n");
      out.write("                        <li class=\"ranker on\">\r\n");
      out.write("                          <p class=\"rank first-rank\">1 st</p>\r\n");
      out.write("                          <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/profile-ex.png\" alt=\"회원 썸네일\">\r\n");
      out.write("                          <p class=\"nickname\">주최자 닉네임 1</p>\r\n");
      out.write("                          <p class=\"star-rating\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/star-on.png\" alt=\"별점\" class=\"star-img\">&nbsp; 4.9</p>\r\n");
      out.write("                        </li>\r\n");
      out.write("\r\n");
      out.write("                        <li class=\"ranker\">\r\n");
      out.write("                          <p class=\"rank second-rank\">2 nd</p>\r\n");
      out.write("                          <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/profile-ex.png\" alt=\"회원 썸네일\">\r\n");
      out.write("                          <p class=\"nickname\">주최자 닉네임 1</p>\r\n");
      out.write("                          <p class=\"star-rating\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/star-on.png\" alt=\"별점\" class=\"star-img\">&nbsp; 4.9</p>\r\n");
      out.write("                        </li>\r\n");
      out.write("\r\n");
      out.write("                        <li class=\"ranker\">\r\n");
      out.write("                          <p class=\"rank third-rank\">3 rd</p>\r\n");
      out.write("                          <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/profile-ex.png\" alt=\"회원 썸네일\">\r\n");
      out.write("                          <p class=\"nickname\">주최자 닉네임 1</p>\r\n");
      out.write("                          <p class=\"star-rating\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/star-on.png\" alt=\"별점\" class=\"star-img\">&nbsp; 4.9</p>\r\n");
      out.write("                        </li>\r\n");
      out.write("\r\n");
      out.write("                        <li class=\"ranker\">\r\n");
      out.write("                          <p class=\"rank least-rank\">4 th</p>\r\n");
      out.write("                          <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/profile-ex.png\" alt=\"회원 썸네일\">\r\n");
      out.write("                          <p class=\"nickname\">주최자 닉네임 1</p>\r\n");
      out.write("                          <p class=\"star-rating\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/star-on.png\" alt=\"별점\" class=\"star-img\">&nbsp; 4.9</p>\r\n");
      out.write("                        </li>\r\n");
      out.write("\r\n");
      out.write("                        <li class=\"ranker\">\r\n");
      out.write("                          <p class=\"rank least-rank\">5 th</p>\r\n");
      out.write("                          <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/profile-ex.png\" alt=\"회원 썸네일\">\r\n");
      out.write("                          <p class=\"nickname\">주최자 닉네임 1</p>\r\n");
      out.write("                          <p class=\"star-rating\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/star-on.png\" alt=\"별점\" class=\"star-img\">&nbsp; 4.9</p>\r\n");
      out.write("                        </li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          <!-- 주최자 랭킹 end -->\r\n");
      out.write("\r\n");
      out.write("          <!-- 카테고리 추천 start -->\r\n");
      out.write("          <div id=\"category-list\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                  <h3 class=\"box-title\">\r\n");
      out.write("                    카테고리<br>\r\n");
      out.write("                    <span class=\"box-sub-title\">관심있는 주제별로 이벤트를 찾아보세요.</span>\r\n");
      out.write("                  </h3>\r\n");
      out.write("                  <ul class=\"category-ul\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a href=\"#\">\r\n");
      out.write("                        <div class=\"blue-background\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/travel-icon.png\" alt=\"\"></div>\r\n");
      out.write("                        <span class=\"category-name\">여행</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a href=\"#\">\r\n");
      out.write("                        <div class=\"blue-background\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/exercise-icon.png\" alt=\"\"></div>\r\n");
      out.write("                        <span class=\"category-name\">운동</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a href=\"#\">\r\n");
      out.write("                        <div class=\"blue-background\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/book-icon.png\" alt=\"\"></div>\r\n");
      out.write("                        <span class=\"category-name\">독서</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a href=\"#\">\r\n");
      out.write("                        <div class=\"blue-background\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/business-icon.png\" alt=\"\"></div>\r\n");
      out.write("                        <span class=\"category-name\">비즈니스</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                  <ul class=\"category-ul\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a href=\"#\">\r\n");
      out.write("                        <div class=\"blue-background\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/language-icon.png\" alt=\"\"></div>\r\n");
      out.write("                        <span class=\"category-name\">언어</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a href=\"#\">\r\n");
      out.write("                        <div class=\"blue-background\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/music-icon.png\" alt=\"\"></div>\r\n");
      out.write("                        <span class=\"category-name\">음악</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a href=\"#\">\r\n");
      out.write("                        <div class=\"blue-background\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/cinema-icon.png\" alt=\"\"></div>\r\n");
      out.write("                        <span class=\"category-name\">영화/공연</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a href=\"#\">\r\n");
      out.write("                        <div class=\"blue-background\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/dance-icon.png\" alt=\"\"></div>\r\n");
      out.write("                        <span class=\"category-name\">댄스</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                  <ul class=\"category-ul\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a href=\"#\">\r\n");
      out.write("                        <div class=\"blue-background\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/volunteer-icon.png\" alt=\"\"></div>\r\n");
      out.write("                        <span class=\"category-name\">봉사활동</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a href=\"#\">\r\n");
      out.write("                        <div class=\"blue-background\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/friend-icon.png\" alt=\"\"></div>\r\n");
      out.write("                        <span class=\"category-name\">사교</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a href=\"#\">\r\n");
      out.write("                        <div class=\"blue-background\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/car-icon.png\" alt=\"\"></div>\r\n");
      out.write("                        <span class=\"category-name\">차/오토바이</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a href=\"#\">\r\n");
      out.write("                        <div class=\"blue-background\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/camera-icon.png\" alt=\"\"></div>\r\n");
      out.write("                        <span class=\"category-name\">사진/영상</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                  <ul class=\"category-ul\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a href=\"#\">\r\n");
      out.write("                        <div class=\"blue-background\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/stadium-icon.png\" alt=\"\"></div>\r\n");
      out.write("                        <span class=\"category-name\">스포츠관람</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a href=\"#\">\r\n");
      out.write("                        <div class=\"blue-background\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/game-icon.png\" alt=\"\"></div>\r\n");
      out.write("                        <span class=\"category-name\">게임</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a href=\"#\">\r\n");
      out.write("                        <div class=\"blue-background\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/cook-icon.png\" alt=\"\"></div>\r\n");
      out.write("                        <span class=\"category-name\">요리</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a href=\"#\">\r\n");
      out.write("                        <div class=\"blue-background\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/pet-icon.png\" alt=\"\"></div>\r\n");
      out.write("                        <span class=\"category-name\">반려동물</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                  <ul class=\"category-ul\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a href=\"#\">\r\n");
      out.write("                        <div class=\"blue-background\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/socialMovement-icon.png\" alt=\"\"></div>\r\n");
      out.write("                        <span class=\"category-name\">사회운동</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a href=\"#\">\r\n");
      out.write("                        <div class=\"blue-background\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/beauty-icon.png\" alt=\"\"></div>\r\n");
      out.write("                        <span class=\"category-name\">뷰티</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a href=\"#\">\r\n");
      out.write("                        <div class=\"blue-background\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/fashion-icon.png\" alt=\"\"></div>\r\n");
      out.write("                        <span class=\"category-name\">패션</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a href=\"#\">\r\n");
      out.write("                        <div class=\"blue-background\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/etc-icon.png\" alt=\"\"></div>\r\n");
      out.write("                        <span class=\"category-name\">기타</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- 카테고리 추천 end -->\r\n");
      out.write("        </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
