/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-03-11 06:22:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1583828957304L));
    _jspx_dependants.put("jar:file:/C:/workspace/KKIRI-JINWOONG/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/kkiri/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.5/js/swiper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\" ></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/jquery.slick/1.6.0/slick.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/common.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/header.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/common.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/index.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/header.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("          \t<div class=\"row\">\r\n");
      out.write("          \t\t<div class=\"col-md-12\">\r\n");
      out.write("                <h1 class=\"logo\"><a href=\"#\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/logo.png\" alt=\"로고\"></a></h1>\r\n");
      out.write("                <div class=\"nav-section\">\r\n");
      out.write("                  <!-- <a href=\"#\" class=\"login-btn\">로그인</a>\r\n");
      out.write("                  <a href=\"signUp.html\">회원가입</a> -->\r\n");
      out.write("                  <a href=\"eventCreate.html\" class=\"createEvent-btn\">이벤트 생성하기</a>\r\n");
      out.write("                  <span class=\"separation\"> | </span>\r\n");
      out.write("                  <a href=\"#\">탐색</a>\r\n");
      out.write("                  <a href=\"#\">고객센터</a>\r\n");
      out.write("                  <div class=\"profile-wrap\">\r\n");
      out.write("                    <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/profile-ex.png\" alt=\"프로필\" class=\"profile-icon\">\r\n");
      out.write("                    <ul class=\"profile-menu\">\r\n");
      out.write("                      <li><a href=\"#\">프로필</a></li>\r\n");
      out.write("                      <li><a href=\"#\">이벤트</a></li>\r\n");
      out.write("                      <li><a href=\"#\">티켓</a></li>\r\n");
      out.write("                      <li><a href=\"#\">로그아웃</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("          \t\t</div>\r\n");
      out.write("          \t</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 프로필 사진 클릭시 세부 메뉴 on/off 이벤트 start-->\r\n");
      out.write("        <script>\r\n");
      out.write("          $(function(){\r\n");
      out.write("            $(\".profile-icon\").on({\r\n");
      out.write("              \"click\" : function(){\r\n");
      out.write("                $(\".profile-menu\").toggleClass(\"on\");\r\n");
      out.write("              }\r\n");
      out.write("            });\r\n");
      out.write("          });\r\n");
      out.write("        </script>\r\n");
      out.write("        <!-- 프로필 사진 클릭시 세부 메뉴 on/off 이벤트 end-->\r\n");
      out.write("\r\n");
      out.write("        <!-- 로그인 팝업 start-->\r\n");
      out.write("        <div id=\"login-popup\" class=\"popup\">\r\n");
      out.write("          <p class=\"popup-title\">\r\n");
      out.write("            로그인\r\n");
      out.write("            <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/close-btn.png\" alt=\"닫기버튼\" class=\"close-popup\">\r\n");
      out.write("          </p>\r\n");
      out.write("          <div class=\"popup-content\">\r\n");
      out.write("            <p class=\"sign-up-title\">아직 회원이 아니신가요?&nbsp;<a href=\"signUp.html\" class=\"link sign-up-link\">회원가입</a></p>\r\n");
      out.write("            <form class=\"login-form-wrap custom-checkbox\" action=\"#\" method=\"post\">\r\n");
      out.write("              <input type=\"text\" name=\"memberId\" placeholder=\"아이디를 입력해주세요.\" autocomplete=\"off\">\r\n");
      out.write("              <input type=\"password\" name=\"memberPwd\" placeholder=\"비밀번호를 입력해주세요.\">\r\n");
      out.write("\r\n");
      out.write("              <input type=\"checkbox\" class=\"custom-control-input\" name=\"rememberId\" id=\"rememberId\">\r\n");
      out.write("              <label class=\"custom-control-label\" for=\"rememberId\">아이디 저장</label>\r\n");
      out.write("              <a href=\"#\" class=\"link find-info-link\">아이디 혹은 비밀번호를 잊으셨나요?</a>\r\n");
      out.write("\r\n");
      out.write("              <button class=\"popup-confirm-btn login-conform-btn\">로그인</button>\r\n");
      out.write("              <button class=\"popup-confirm-btn another-btn\">구글 아이디로 로그인</button>\r\n");
      out.write("              <button class=\"popup-confirm-btn another-btn\">페이스북 아이디로 로그인</button>\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"popup-shadow\"></div>\r\n");
      out.write("        <!-- 로그인 팝업 end-->\r\n");
      out.write("\r\n");
      out.write("      <script>\r\n");
      out.write("        // 로그인 팝업 이벤트\r\n");
      out.write("        $(\".login-btn\").on({\r\n");
      out.write("          click : function(){\r\n");
      out.write("            $(\".popup-shadow, #login-popup\").show(0);\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("        $(\".close-popup, .popup-shadow\").on({\r\n");
      out.write("          click : function(){\r\n");
      out.write("            $(\".popup-shadow, #login-popup\").hide(0);\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("      </script>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"></script>\r\n");
      out.write("\t<script\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
